// ----------------------------------------------------------
/*!
	\class AClipboardDriverMacOS
	\title
	\brief Template file files/cppheader/file.h

	\list
	\li @notice Template file classes/file.h
	\li @copyright Arboreus (http://arboreus.systems)
	\li @author Alexandr Kirilov (http://alexandr.kirilov.me)
	\li @created 13/09/2026 at 09:16:31
	\endlist
*/
// ----------------------------------------------------------

// Class header
#include "aclipboarddrivermacos.h"

// Namespace
using namespace ARB;


// -----------
/*!
	\fn

	Doc.
*/

AClipboardDriverMacOS::AClipboardDriverMacOS(QObject* parent) : AClipboardDriver(parent) {

	_A_DEBUG << "AClipboardDriverMacOS created";
}


// -----------
/*!
	\fn

	Doc.
*/

AClipboardDriverMacOS::AClipboardDriverMacOS(QClipboard* inClipboard, QObject* parent)
: AClipboardDriver(inClipboard,parent) {

	_A_DEBUG << "AClipboardDriverMacOS created with clipboard";
}


// -----------
/*!
	\fn

	Doc.
*/

AClipboardDriverMacOS::~AClipboardDriverMacOS(void) {

	_A_DEBUG << "AClipboardDriverMacOS deleted";
}


// -----------
/*!
	\fn

	Doc.
*/

void AClipboardDriverMacOS::mTextCopySensitiveTo(QString inText) {

	QByteArray emptyFlag;

	QMimeData* mimeData = new QMimeData();
	mimeData->setText(inText);
	mimeData->setData(QStringLiteral("org.nspasteboard.ConcealedType"),emptyFlag);
	mimeData->setData(QStringLiteral("org.nspasteboard.TransientType"),emptyFlag);
	mimeData->setData(QStringLiteral("org.nspasteboard.AutoGeneratedType"),emptyFlag);

	pClipboard->setMimeData(mimeData);
}


// -----------
/*!
	\fn

	Doc.
*/

void AClipboardDriverMacOS::mClear(void) {

	pClipboard->clear(QClipboard::Clipboard);

	QMimeData* emptyData = new QMimeData();
	emptyData->setData("org.nspasteboard.TransientType", QByteArray());
	emptyData->setData("org.nspasteboard.ConcealedType", QByteArray());

	pClipboard->setMimeData(emptyData);

	_A_DEBUG << "Clipboard cleared";
}
